name: flutter_custom_tabs
description: Flutter plugin for seamlessly displaying web content using Chrome Custom Tabs.
version: 1.2.0
homepage: https://github.com/droibit/flutter_custom_tabs

# TODO: To be removed before v2.0.0 release
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter_custom_tabs_platform_interface: ^1.2.0
  # TODO: To be removed before v2.0.0 release
  flutter_custom_tabs_platform_interface: 
    path: ../flutter_custom_tabs_platform_interface
  # flutter_custom_tabs_web: ^1.1.0
  # TODO: To be removed before v2.0.0 release  
  flutter_custom_tabs_web: 
    path: ../flutter_custom_tabs_web
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  flutter_lints: ^2.0.1
  plugin_platform_interface: ^2.1.5

flutter:
  plugin:
    platforms:
      android:
        package: com.github.droibit.flutter.plugins.customtabs
        pluginClass: CustomTabsPlugin
      ios:
        pluginClass: CustomTabsPlugin
      web:
        default_package: flutter_custom_tabs_web