name: flutter_custom_tabs_web
description: Web platform implementation of flutter_custom_tabs.
version: 1.1.0
homepage: https://github.com/droibit/flutter_custom_tabs

# TODO: To be deleted before v2.0.0 release.
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter 
  # flutter_custom_tabs_platform_interface: ^1.1.0
  # TODO: To be removed before v2.0.0 release
  flutter_custom_tabs_platform_interface:
    path: ../flutter_custom_tabs_platform_interface
  meta: ^1.9.1
  url_launcher_platform_interface: ^2.0.3
  url_launcher_web: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: CustomTabsPlugin
        fileName: flutter_custom_tabs_web.dart